const shadow = require('./shadow')

module.exports = {
  position: x => ['position', x || 'relative'],
  relative: _ => ['position', 'relative'],
  absolute: _ => ['position', 'absolute'],
  fill: (x) => [
    ['position', 'absolute'],
    ['zIndex', 100],
    ['top', 0],
    ['right', 0],
    ['bottom', 0],
    ['left', 0],
  ],
  bg: (x) => ['backgroundColor', x || 'green'],
  h: x => ['height', x],
  centerCenter: (x) => [['justifyContent', 'center'], ['alignItems', 'center']],
  startCenter: (x) => [['justifyContent', 'flex-start'], ['alignItems', 'center']],
  startStart: (x) => [['justifyContent', 'flex-start'], ['alignItems', 'flex-start']],
  w: x => ['width', x],
  wrap: () => ['flexWrap', 'wrap'],
  display: (x) => ['display', x || 'flex'],
  flex: (x) => ['flex', x || 1],
  top: _ => ['top', x || 20],
  left: _ => ['left', x || 20],
  right: _ => ['right', x || 20],
  bottom: _ => ['bottom', x || 20],
  minWidth: _ => ['minWidth', x || 20],
  minw: _ => ['minWidth', x || 20],
  maxWidth: _ => ['maxWidth', x || 20],
  minHeight: _ => ['minHeight', x || 20],
  minh: _ => ['minHeight', x || 20],
  maxHeight: _ => ['maxHeight', x || 20],
  maxh: _ => ['maxHeight', x || 20],
  margin: _ => ['margin', x || 20],
  marginVertical: _ => ['marginVertical', x || 20],
  mvert: _ => ['marginVertical', x || 20],
  marginHorizontal: _ => ['marginHorizontal', x || 20],
  mhorz: _ => ['marginHorizontal', x || 20],
  marginTop: _ => ['marginTop', x || 20],
  mt: _ => ['marginTop', x || 20],
  marginBottom: _ => ['marginBottom', x || 20],
  mb: _ => ['marginBottom', x || 20],
  marginLeft: _ => ['marginLeft', x || 20],
  ml: _ => ['marginLeft', x || 20],
  marginRight: _ => ['marginRight', x || 20],
  mr: _ => ['marginRight', x || 20],
  marginStart: _ => ['marginStart', x || 20],
  marginEnd: _ => ['marginEnd', x || 20],
  padding: _ => ['padding', x || 20],
  paddingVertical: _ => ['paddingVertical', x || 20],
  pvert: _ => ['paddingVertical', x || 20],
  paddingHorizontal: _ => ['paddingHorizontal', x || 20],
  phorz: _ => ['paddingHorizontal', x || 20],
  paddingTop: _ => ['paddingTop', x || 20],
  pt: _ => ['paddingTop', x || 20],
  paddingBottom: _ => ['paddingBottom', x || 20],
  pb: _ => ['paddingBottom', x || 20],
  paddingLeft: _ => ['paddingLeft', x || 20],
  pl: _ => ['paddingLeft', x || 20],
  paddingRight: _ => ['paddingRight', x || 20],
  pr: _ => ['paddingRight', x || 20],
  paddingStart: _ => ['paddingStart', x || 20],
  paddingEnd: _ => ['paddingEnd', x || 20],
  borderWidth: _ => ['borderWidth', x || 20],
  borderTopWidth: _ => ['borderTopWidth', x || 20],
  borderStartWidth: _ => ['borderStartWidth', x || 20],
  borderEndWidth: _ => ['borderEndWidth', x || 20],
  borderRightWidth: _ => ['borderRightWidth', x || 20],
  borderBottomWidth: _ => ['borderBottomWidth', x || 20],
  borderLeftWidth: _ => ['borderLeftWidth', x || 20],
  scaleX: x => ['scaleX', x],
  scaleY: x => ['scaleY', x],
  rotation: x => ['rotation', x],
  translateX: x => ['translateX', x],
  translateY: x => ['translateY', x],
  opacity: x => ['opacity', x],
  color: x => ['color', x],
  fontSize: x => ['fontSize', x],
  fs: x => ['fontSize', x],
  fontWeight: x => ['fontWeight', x],
  fw: x => ['fontWeight', x],
  letterSpacing: x => ['letterSpacing', x],
  ls: x => ['letterSpacing', x],
  lineHeight: x => ['lineHeight', x],
  lh: x => ['lineHeight', x],
  textAlign: x => ['textAlign', x],
  text: x => ['textAlign', x],
  ...shadow
}