const shadow = require('./shadow')

module.exports = {
  position: x => ['position', x || 'relative'],
  relative: x => ['position', 'relative'],
  absolute: x => ['position', 'absolute'],
  fill: (x) => [
    ['position', 'absolute'],
    ['zIndex', 100],
    ['top', 0],
    ['right', 0],
    ['bottom', 0],
    ['left', 0],
  ],
  bg: (x) => ['backgroundColor', x || 'green'],
  h: x => ['height', x],
  centerCenter: (x) => [['justifyContent', 'center'], ['alignItems', 'center']],
  startCenter: (x) => [['justifyContent', 'flex-start'], ['alignItems', 'center']],
  startStart: (x) => [['justifyContent', 'flex-start'], ['alignItems', 'flex-start']],
  w: x => ['width', x],
  wrap: () => ['flexWrap', 'wrap'],
  display: (x) => ['display', x || 'flex'],
  flex: (x) => ['flex', x || 1],
  top: x => ['top', x || 20],
  left: x => ['left', x || 20],
  right: x => ['right', x || 20],
  bottom: x => ['bottom', x || 20],
  minWidth: x => ['minWidth', x || 20],
  minw: x => ['minWidth', x || 20],
  maxWidth: x => ['maxWidth', x || 20],
  minHeight: x => ['minHeight', x || 20],
  minh: x => ['minHeight', x || 20],
  maxHeight: x => ['maxHeight', x || 20],
  maxh: x => ['maxHeight', x || 20],
  margin: x => ['margin', x || 20],
  marginVertical: x => ['marginVertical', x || 20],
  mvert: x => ['marginVertical', x || 20],
  marginHorizontal: x => ['marginHorizontal', x || 20],
  mhorz: x => ['marginHorizontal', x || 20],
  marginTop: x => ['marginTop', x || 20],
  mt: x => ['marginTop', x || 20],
  marginBottom: x => ['marginBottom', x || 20],
  mb: x => ['marginBottom', x || 20],
  marginLeft: x => ['marginLeft', x || 20],
  ml: x => ['marginLeft', x || 20],
  marginRight: x => ['marginRight', x || 20],
  mr: x => ['marginRight', x || 20],
  marginStart: x => ['marginStart', x || 20],
  marginEnd: x => ['marginEnd', x || 20],
  padding: x => ['padding', x || 20],
  paddingVertical: x => ['paddingVertical', x || 20],
  pvert: x => ['paddingVertical', x || 20],
  paddingHorizontal: x => ['paddingHorizontal', x || 20],
  phorz: x => ['paddingHorizontal', x || 20],
  paddingTop: x => ['paddingTop', x || 20],
  pt: x => ['paddingTop', x || 20],
  paddingBottom: x => ['paddingBottom', x || 20],
  pb: x => ['paddingBottom', x || 20],
  paddingLeft: x => ['paddingLeft', x || 20],
  pl: x => ['paddingLeft', x || 20],
  paddingRight: x => ['paddingRight', x || 20],
  pr: x => ['paddingRight', x || 20],
  paddingStart: x => ['paddingStart', x || 20],
  paddingEnd: x => ['paddingEnd', x || 20],
  borderWidth: x => ['borderWidth', x || 20],
  borderTopWidth: x => ['borderTopWidth', x || 20],
  borderStartWidth: x => ['borderStartWidth', x || 20],
  borderEndWidth: x => ['borderEndWidth', x || 20],
  borderRightWidth: x => ['borderRightWidth', x || 20],
  borderBottomWidth: x => ['borderBottomWidth', x || 20],
  borderLeftWidth: x => ['borderLeftWidth', x || 20],
  scaleX: x => ['scaleX', x],
  scaleY: x => ['scaleY', x],
  rotation: x => ['rotation', x],
  translateX: x => ['translateX', x],
  translateY: x => ['translateY', x],
  opacity: x => ['opacity', x],
  color: x => ['color', x],
  fontSize: x => ['fontSize', x],
  fs: x => ['fontSize', x],
  fontWeight: x => ['fontWeight', x],
  fw: x => ['fontWeight', x],
  letterSpacing: x => ['letterSpacing', x],
  ls: x => ['letterSpacing', x],
  lineHeight: x => ['lineHeight', x],
  lh: x => ['lineHeight', x],
  textAlign: x => ['textAlign', x],
  text: x => ['textAlign', x],
  ...shadow
}